name: backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - django
  - psycopg2
  - python-dotenv
  - djangorestframework
  - django-cors-headers
  - pip
  - whitenoise=6.4.0
  - python-dotenv
  - colorama=0.4.6
  - drf-spectacular
  - pillow
  - pip:
      - django-auth-adfs
      - social-auth-app-django==5.4.3
      - wfastcgi==3.0.0



